# Comando para executar: docker compose up --build --force-recreate
version: '3.9'

networks:
  api-food-network:
    driver: bridge

volumes:
  pgdata:
  mongodata:

services:
  db_postgres:
    container_name: db_postgres
    image: 'postgres:13.4'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apifood
    ports:
      - "5432:5432"
      - '5005:5005'
    networks:
      - api-food-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    container_name: mongo_db
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=api-food
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    networks:
      - api-food-network
    volumes:
      - mongodata:/data/db

  api-food:
    container_name: api-food
    image: api-food
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8088:8088'
      - '5006:5006'
    environment:
      PORT: 8088
      DB_URL: db_postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: apifood
      NOTIFICATION_URL: https://pure-daily-grackle.ngrok-free.app/order/notifications
      ADDITIONAL_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5006 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
    networks:
      - api-food-network
    depends_on:
      - db_postgres
      - mongodb

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    networks:
      - api-food-network
    depends_on:
      - api-food