apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-food
  labels:
    app: api-food
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-food
  template:
    metadata:
      labels:
        app: api-food
    spec:
      containers:
        - name: api-food
          image: josevitordurante/api-food:latest
          ports:
            - containerPort: 8088
          env:
            - name: PORT
              value: "8088"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-food-config
                  key: DB_NAME
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: api-food-config
                  key: DB_URL
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-food-config
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: api-food-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: api-food-config
                  key: DB_PASSWORD
            - name: NOTIFICATION_URL
              valueFrom:
                configMapKeyRef:
                  name: api-food-config
                  key: NOTIFICATION_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
