name: "Terraform Destroy"

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name techchallenge --region us-east-1

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v4.0.0
        with:
          version: latest

      - name: Destroy Application
        run: |
          kubectl delete deployments --all -n default
          kubectl delete replicasets --all -n default
          kubectl delete statefulsets --all -n default
          kubectl delete services --all -n default
          kubectl delete pods --all -n default
          kubectl delete pvc --all -n default
          kubectl delete hpa --all -n default
          kubectl delete pv --all
          kubectl delete role --all
          kubectl delete rolebinding --all
          kubectl delete configmap --all
